load("//tools:cpplint.bzl", "cpplint")
load("//tools:apollo_package.bzl", "apollo_package")

package(default_visibility = ["//visibility:public"])

# Tasks module - contains individual planning tasks
# Individual task BUILD files are in their respective subdirectories

apollo_package()

cpplint()

