load("//tools:cpplint.bzl", "cpplint")
load("//tools:apollo_package.bzl", "apollo_package")

package(default_visibility = ["//visibility:public"])

# Planners module - contains different planning algorithms
# Individual planner BUILD files are in their respective subdirectories

apollo_package()

cpplint()

