load("//tools:cpplint.bzl", "cpplint")
load("//tools:apollo_package.bzl", "apollo_package")

package(default_visibility = ["//visibility:public"])

# Scenarios module - contains different driving scenarios
# Individual scenario BUILD files are in their respective subdirectories

apollo_package()

cpplint()

