load("//tools:cpplint.bzl", "cpplint")
load("//tools:apollo_package.bzl", "apollo_package")

package(default_visibility = ["//visibility:public"])

# Traffic Rules module - contains traffic rule implementations
# Individual traffic rule BUILD files are in their respective subdirectories

apollo_package()

cpplint()

